config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'productos/nuevo', to:'productos#new' 
  post 'productos/nuevo', to:'productos#create', as: 'productos_crear' 
  get 'productos/:id/editar', to:'productos#edit', as: 'productos_editar' 
  put 'productos/editar', to:'productos#update', as: 'productos_actualizar'  
  put 'productos/:id/borrar',   to:'productos#destroy', as: 'productos_borrar'
  put 'productos/:id/activar',   to:'productos#activar', as: 'productos_activar'

  resources :rubros
  resources :marcas

  root 'productos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
    has_many :productos
end

app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :marca
    belongs_to :rubro
end

app/models/rubro.rb
class Rubro < ApplicationRecord
    has_many :productos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marca_params
      params.require(:marca).permit(:nombre)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index
  	@lista = Producto.all
  end

  def new
    @item=Producto.new
  end

  def create
    item=Producto.new
    item.id=params['producto']['id']
    item.nombre=params['producto']['nombre']
    item.cant_min=params['producto']['cant_min']
    item.cant_act=params['producto']['cant_act']
    item.precio=params['producto']['precio']
    item.activo=params['producto']['activo']
    item.marca_id = params['producto']['marca_id']
    item.rubro_id = params['producto']['rubro_id']
    item.save
    redirect_to root_path	
  end

  def edit
    @item=Producto.find(params['id'])
  end

  def update
    item=Producto.find(params['producto']['id'])
    item.nombre=params['producto']['nombre']
    item.cant_min=params['producto']['cant_min']
    item.cant_act=params['producto']['cant_act']
    item.precio=params['producto']['precio']
    item.activo=params['producto']['activo']
    item.marca_id = params['producto']['marca_id']
    item.rubro_id = params['producto']['rubro_id']
    item.save
    redirect_to root_path
  end

  def destroy
    item=Producto.find(params['id'])
    item.activo = 1
    item.save
    redirect_to root_path
  end
end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]

  # GET /rubros
  # GET /rubros.json
  def index
    @rubros = Rubro.all
  end

  # GET /rubros/1
  # GET /rubros/1.json
  def show
  end

  # GET /rubros/new
  def new
    @rubro = Rubro.new
  end

  # GET /rubros/1/edit
  def edit
  end

  # POST /rubros
  # POST /rubros.json
  def create
    @rubro = Rubro.new(rubro_params)

    respond_to do |format|
      if @rubro.save
        format.html { redirect_to @rubro, notice: 'Rubro was successfully created.' }
        format.json { render :show, status: :created, location: @rubro }
      else
        format.html { render :new }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubros/1
  # PATCH/PUT /rubros/1.json
  def update
    respond_to do |format|
      if @rubro.update(rubro_params)
        format.html { redirect_to @rubro, notice: 'Rubro was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubro }
      else
        format.html { render :edit }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubros/1
  # DELETE /rubros/1.json
  def destroy
    @rubro.destroy
    respond_to do |format|
      format.html { redirect_to rubros_url, notice: 'Rubro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rubro_params
      params.require(:rubro).permit(:nombre, :perecedero)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/rubros_helper.rb
module RubrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>

  <body style="background-image: url('https://i0.wp.com/i.pinimg.com/originals/23/79/76/237976db7a8cb35af645830b6718e4ef.jpg');">
  
  
  <nav class="navbar navbar-expand-lg  navbar-light bg-info ">
  <div class="container-fluid">
    <%= link_to "Productos", root_path, :class=>"navbar-brand"  %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Marcas", marcas_path, :class=>"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rubros", rubros_path, :class=>"nav-link active" %>
        </li>
  <% if user_signed_in? %>
  <li class="nav-item">
    <%= current_user.email %>
  </li>
  <li class="nav-item">
    <%= link_to "Cerrar sesión", destroy_user_session_path, method: :destroy, :class=>"nav-link active" %>
  </li>
  <% else %>
  <li class="nav-item">
    <%= link_to "Iniciar sesión", new_user_session_path, :class=>"nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "Crear cuenta", new_user_registration_path, :class=>"nav-link active" %>
  </li>
  <% end %>

    </div>
  </div>
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/marcas/_form.html.erb
<div class="container bg-success">
<%= form_with(model: marca, local: true) do |form| %>
  <% if marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
        <% marca.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <p>
 <label>Nombre</label> <br>
    <%= form.text_field :nombre, :class => 'form-control' %>
 </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>

app/views/marcas/edit.html.erb
<h1>Editar Marca</h1>

<%= render 'form', marca: @marca, :class => "btn btn-success" %>

<%= link_to 'Mostrar', @marca, :class => "btn btn-success" %> |
<%= link_to 'Atras', marcas_path, :class => "btn btn-info" %>

app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="container">
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th><th>Nombre</th><th colspan="3"></th>
                <th class="text-center"><%= link_to 'Nuevo', new_marca_path, :class => "btn btn-primary" %></th>
            </tr>
        </thead>
        <tbody>
          <% @marcas.each do |marca| %>
            <tr>
              <td><%= marca.nombre %></td>
              <td><%= link_to 'Mostrar', marca, :class => "btn btn-warning" %></td>
              <td><%= link_to 'Editar', edit_marca_path(marca), :class => "btn btn-success" %></td>
            </tr>   
          <% end %>
        </tbody>
    </table>
</div>

app/views/marcas/new.html.erb
<h1>Nueva Marca</h1>

<%= render 'form', marca: @marca, :class => "btn btn-success" %>

<%= link_to 'Atras', marcas_path, :class => "btn btn-info" %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container bg-warning">
<p>
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>

<%= link_to 'Editar', edit_marca_path(@marca), :class => "btn btn-success" %> |
<%= link_to 'Atras', marcas_path, :class => "btn btn-info" %>
</div>

app/views/productos/create.html.erb
<h1>Productos#create</h1>
<p>Find me in app/views/productos/create.html.erb</p>

app/views/productos/destroy.html.erb
<h1>Productos#destroy</h1>
<p>Find me in app/views/productos/destroy.html.erb</p>

app/views/productos/edit.html.erb
<div class="container">
<h1 class="m-3">Editar producto</h1>
<%= form_with scope: @item, url: productos_actualizar_path, method: :PUT do |f| %>
 <%= f.hidden_field  :id %>  
 <p>
 <label>Nombre</label> <br>
 <%= f.text_field :nombre, :class => 'form-control' %>
 </p>
 <p>
 <label>Cantidad minima</label> <br>
 <%= f.text_field :cant_min, :class => 'form-control' %>
 </p>
 <p>
 <label>Cantidad actual</label> <br>
 <%= f.text_field :cant_act, :class => 'form-control' %>
 </p>
 <p>
 <label>Precio</label> <br>
 <%= f.text_field :precio, :class => 'form-control' %>
 </p>
 <p>
 <label>Activo</label> <br>
 <%= f.check_box :activo, :class => 'form-control' %>
 </p>
 <p><label>Marca</label>
  <%= f.collection_select :marca_id, Marca.all, :id, :nombre, {}, { :class => 'form-control' } %> 
 </p>
  <p><label>Rubro</label>
  <%= f.collection_select :rubro_id, Rubro.all, :id, :nombre, {}, { :class => 'form-control' } %> 
 </p>
 <%= f.submit "Enviar", disable_with: 'Submiting...', :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/productos/index.html.erb
<div class="container">
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th><th>Nombre</th><th>Cantidad minima</th><th>Cantidad actual</th><th>precio</th><th>Marca</th><th>Rubro</th><th>Estado</th>
                <th class="text-center"><%= link_to 'Nuevo', productos_nuevo_path, :class => "btn btn-primary" %></th>
            </tr>
        </thead>
        <tbody>
        <%  @lista.each do |item|  %>
            <tr>
            <td><%= item.id %></td>
            <td><%= item.nombre %></td>
            <td><%= item.cant_min %></td>
            <td><%= item.cant_act %></td>
            <td><%= item.precio %></td>
            <td><%= item.marca_id %></td>
            <td><%= item.rubro_id %></td>
            <td><%= item.activo %></td>
            <td class="text-center"><%= link_to 'Editar', productos_editar_path(item.id), :class => "btn btn-success" %></td>
            
            </tr>   
        <% end %>
        </tbody>
    </table>
</div>

app/views/productos/new.html.erb
<div class="container bg-success">
<h1 class="m-3">Nuevo producto</h1>
<%= form_with scope: @item, url: productos_crear_path do |f| %>
 <%= f.hidden_field  :id %>  
 <p>
 <label>Nombre</label> <br>
 <%= f.text_field :nombre, :class => 'form-control' %>
 </p>
 <p>
 <label>Cantidad minima</label> <br>
 <%= f.text_field :cant_min, :class => 'form-control' %>
 </p>
 <p>
 <label>Cantidad actual</label> <br>
 <%= f.text_field :cant_act, :class => 'form-control' %>
 </p>
 <p>
 <label>Precio</label> <br>
 <%= f.text_field :precio, :class => 'form-control' %>
 </p>
 <p>
 <label>Activo</label> <br>
 <%= f.check_box :activo, :class => 'form-control' %>
 </p>
 
 <p><label>Marca</label>
  <%= f.collection_select :marca_id, Marca.all, :id, :nombre, {}, { :class => 'form-control' } %> 
 </p>
  <p><label>Rubro</label>
  <%= f.collection_select :rubro_id, Rubro.all, :id, :nombre, {}, { :class => 'form-control' } %> 
 </p>
 <%= f.submit "Enviar", disable_with: 'Submiting...', :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/productos/update.html.erb
<h1>Productos#update</h1>
<p>Find me in app/views/productos/update.html.erb</p>

app/views/rubros/_form.html.erb
<div class="container bg-success">
<%= form_with(model: rubro, local: true) do |form| %>
  <% if rubro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubro.errors.count, "error") %> prohibited this rubro from being saved:</h2>

      <ul>
        <% rubro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
 <label>Nombre</label> <br>
    <%= form.text_field :nombre, :class => 'form-control' %>
</p>

<p>
 <label>Perecedero</label> <br>
    <%= form.check_box :perecedero %>
</p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/rubros/edit.html.erb
<h1>Editar Rubro</h1>

<%= render 'form', rubro: @rubro %>

<%= link_to 'Mostrar', @rubro, :class => "btn btn-success" %> |
<%= link_to 'Atras', rubros_path, :class => "btn btn-info" %>

app/views/rubros/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th><th>Nombre</th><th>Perecedero</th><th colspan="3"></th>
                <th class="text-center"><%= link_to 'Nuevo', new_rubro_path, :class => "btn btn-primary" %></th>
            </tr>
        </thead>
        <tbody>
          <% @rubros.each do |rubro| %>
            <tr>
              <td><%= rubro.nombre %></td>
              <td><%= rubro.perecedero %></td>
              <td><%= link_to 'Mostrar', rubro, :class => "btn btn-warning" %></td>
              <td><%= link_to 'Editar', edit_rubro_path(rubro), :class => "btn btn-success" %></td>
            </tr>   
          <% end %>
        </tbody>
    </table>
</div>

app/views/rubros/new.html.erb
<h1>Nuevo Rubro</h1>

<%= render 'form', rubro: @rubro, :class => "btn btn-success" %>

<%= link_to 'Atras', rubros_path, :class => "btn btn-info" %>

app/views/rubros/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container bg-warning">
<p>
  <strong>Nombre:</strong>
  <%= @rubro.nombre %>
</p>

<p>
  <strong>Perecedero:</strong>
  <%= @rubro.perecedero %>
</p>

<%= link_to 'Editar', edit_rubro_path(@rubro), :class => "btn btn-success" %> |
<%= link_to 'Atras', rubros_path, :class => "btn btn-info" %>
</div>